version: "3.7"
services:
    spark-demo:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./:/home/jovyan
      ports:
        - 8888:8888
      container_name: spark-demo
